### ISSUE TITLE
using xcode run swift for tensorflow problems？

### ISSUE THREAD

**Issue by zhanyongzhe** [tensorflow/swift#276]
xcode：10.3
swift：5.0.1

swift command executed tensorflow successfully

dyld: Library not loaded: @rpath/libswiftPython.dylib
  Referenced from: /Users/yongzhezhang/Library/Developer/Xcode/DerivedData/test1-byapzqhnnupcwpbtkzxkpphhjgdq/Build/Products/Debug/test1
  Reason: image not found

**Comment by mko-io** [comment]
same problem here

**Comment by dan-zheng** [comment]
Did you run into this error by creating an Xcode project via Xcode?
(`Xcode > File > New > Project > ...`)

Unfortunately, Xcode is known to have issues with Swift for TensorFlow toolchains. Adding support is difficult because Xcode is closed-source and out of our control.

Consider creating a SwiftPM package instead ([mailing list discussion](https://groups.google.com/a/tensorflow.org/d/msg/swift/plU_x_7WOCk/kq1Da8YWAgAJ)):
```bash
# Download a Swift for TensorFlow toolchain from
# https://github.com/tensorflow/swift/blob/master/Installation.md.

$ mkdir Foo
$ cd Foo
$ swift package init --type executable
# Edit sources to import and use TensorFlow.
$ swift test # This should work!
```

**Comment by dan-zheng** [comment]
Closing this issue since there hasn't been activity.
If you still encounter this issue, please feel free to reopen it or file a new issue!
