### ISSUE TITLE
[question] Linux compatibility

### ISSUE THREAD

**Issue by tanner0101** [tensorflow/swift#3]
Does this package work on non-Darwin platforms?

**Comment by dan-zheng** [comment]
Yes. Currently, we build on Ubuntu 14.04 and Ubuntu 16.04 and provide [pre-built packages](https://github.com/tensorflow/swift/blob/master/Installation.md) for those platforms.

Theoretically, the Swift build scripts support other non-Darwin platforms (FreeBSD, etc) but we haven't added TensorFlow support for them.

**Comment by dan-zheng** [comment]
Speaking of other platforms, we do plan on adding iOS support at some point!
TensorFlow provides [iOS build instructions](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/ios#building-the-tensorflow-ios-libraries-from-source) so it should be feasible. 😀

**Comment by coder543** [comment]
Swift is a fine language, but I would also point out that Swift doesn't support Windows... which is possibly the largest platform used by data scientists. I'm confused as to why tensorflow selected Swift over Rust, when Rust has uniformly better support for Windows and Linux than Swift. Rust also supports WASM better than any other language, with the possible exception of C, so using Rust would have furthered Google's long-term goal of supporting tensorflow on the web better than Swift is currently poised to do.

All of these problems can be resolved with enough effort, but I think it would have taken less effort to improve the ergonomics of Rust than to fix all of the issues Swift presents for tensorflow.

Swift is way more sustainable than Python, due to just how slow Python is, so I'm glad to see effort being put into this project, I just wonder if this is really the most _objective_ choice for the project. If those issues mentioned above with Swift are about to be fixed in rapid succession, then that's great! I expect Swift will be great for tensorflow users then.

**Comment by dan-zheng** [comment]
@tanner0101 
One last point: I noticed you used the word "package", but Swift for TensorFlow is actually a copy of the Swift compiler that adds first-class language support for machine learning. This distinguishes Swift for TensorFlow from machine learning frameworks like PyTorch, which are implemented as libraries.

We chose this approach because we believe first-class language support enables the best of performance and usability, and will open up many research possibilities. Please read our [design overview](https://github.com/tensorflow/swift/blob/master/docs/DesignOverview.md) for more information.

**Comment by rxwei** [comment]
Hi @coder543, in this document we presented our objective decision process. 
[Why Swift for TensorFlow?](https://github.com/tensorflow/swift/blob/master/docs/WhySwiftForTensorFlow.md)

Picking the best language design and balancing the trade-offs is a more fundamental problem. We have to take into account of the design principles of the language, e.g. progress disclosure of complexity, which is far more important than just "what platforms the language supports".  (If I considered the latter to be the deciding factor, I would've chosen C.)

The Swift open source community has worked on Windows support and bare metal support, although they are not nearly ready for general use. We'll be very happy to work with the community to develop support for more platforms at certain point.

If you have further questions regarding the language of choice, please feel free to discuss that on the mailing list. Thank you!

**Comment by coder543** [comment]
Yes, I read that, but I was hoping for more elaboration around the points that I had raised.

The additional learning curve for Rust (versus Swift) is arguably small compared to the learning curve of asking data scientists to erase Windows and install a Linux distro, for example. (Running a VM won't work because direct GPU access is important.) The ownership model _really is_ irrelevant to why Rust would be a better choice here, so I agree with the document on that. The reason why Swift doesn't make sense is all about platform support, which I didn't see addressed in that document. It's easy to underestimate how much effort went into making Rust support all these major OSes as well as it does.

I wasn't even planning to respond if any of my points had been addressed at all, but none of my points were addressed, so I felt the need to clarify here a little bit. I feel that properly supporting Windows is immensely important if Google wants to support data scientists. Supporting Linux and WASM well from day one would be an added bonus. Swift support for Linux is very minimalistic at this point.

This decision seems to have already been made, and I've stated my piece, so it's whatever.

**Comment by lattner** [comment]
Thanks for the input @coder543.  That document is not intended to be a debate about the suitability of languages for arbitrary purposes, it was just intended to explain the process of how we ended up here - we understand that other people coming from other perspectives would see different tradeoffs and could end up in different places.

In any case, as stated, we would really love to see the techniques applied in other languages and domains, but we're going to continue pursuing this one.  Thanks!

**Comment by JacquisLewis** [comment]
Swift has the tech and momentum for the realization of an Isomorphic Development <https://www.google.com/search?client=safari&rls=en&q=isomorphic+development&ie=UTF-8&oe=UTF-8> dream scenario.  One language to do everything because, "Swift has the audacious goal of spanning all the way from low-level systems programming to high-level scripting,…”

Over time the language will gain all the properties to be used in any kind of development from embedded to cloud

**Comment by JacquisLewis** [comment]
Whoops

**Comment by iiSeymour** [comment]
@dan-zheng is there an issue/twitter account to follow to get updated on iOS support?

**Comment by lattner** [comment]
The toolchain is primarily oriented around training, not on-device inference. We are interested in hooking up TF Lite support.  Please ask on the mailing list, or file a new bug to track TFLite integration, thanks!
