### ISSUE TITLE
[ISSUE] Python split( ) function

### ISSUE THREAD

**Issue by rakesh4real** [tensorflow/swift#325]
Python split function not working correctly. 

![p](https://user-images.githubusercontent.com/45640029/69431057-f2360400-0d5c-11ea-9e5d-1a9057af9278.PNG)

**Comment by dan-zheng** [comment]
Hi @rakesh4real:

```swift
for i in 0..<ns.count {
  print(ns[i])
}
```

This code doesn't work because `i` has type `Int` but [`PythonObject.subscript(_:)`](https://www.tensorflow.org/swift/api_docs/Structs/PythonObject#subscript_:_1) takes a `PythonObject` representing an index value. [`PythonObject.Index` is `PythonObject`](https://www.tensorflow.org/swift/api_docs/Structs/PythonObject#index). 

---

Swift actually has an elegant solution to this! Use `ns.indices` instead of `0..<ns.count`.

The `Collection` protocol defines a bunch of requirements for manipulating indices, including [`Collection.indices`](https://developer.apple.com/documentation/swift/collection/1641719-indices). Using these APIs avoids unexpected/incorrect behavior, and leads to shorter code here:

```swift
import Python
var string: PythonObject = "hello world"
var slices = string.split(separator: " ")
var ns = slices[0]
for i in ns.indices { // notice `ns.indices` here
  print(ns[i])
}
// h
// e
// l
// l
// o
```

For reference: here's a related [mailing list reply](https://groups.google.com/a/tensorflow.org/d/msg/swift/GgXaKufF3Js/EsMv0P8lBQAJ) on Swift indexing APIs.
