### ISSUE TITLE
issue with new colab notebook 3 tab and TensorFlow swift

### ISSUE THREAD

**Issue by power9799** [tensorflow/swift#376]
When I'm open a new notebook 3 on google colab and copy the code ( import Python
%include "EnableIPythonDisplay.swift" ) onto the notebook; it gives an error saying invalid syntax.
It seems to only work when I open the walkthrough or using a blank_swift.ipynb.

**Comment by ematejska** [comment]
Did you open a new "Python 3" notebook?  You can check by looking at Runtime->Change Runtime Type.  You need to use the blank_swift.ipynb if you want to create a colab with a Swift runtime for now.

**Comment by power9799** [comment]
hi, on change run time, there is no option to switch to swift runtime; only python 2 or 3.
Also when I'm running the walkthrough, it giving an error saying Line 43: Could not find "TutorialDatasetCSVAPI.swift". Searched ['/swift/swift-jupyter', '/content'].

**Comment by ematejska** [comment]
@power9799 That is the expected behavior right now (no option to switch to Swift Runtime). Please use the blank notebook to get a new notebook going (sorry for the trouble).  How are you running your notebook?  Is it with: https://colab.research.google.com/github/tensorflow/swift/blob/master/docs/site/tutorials/model_training_walkthrough.ipynb?  You must make sure to run the part of the notebook that file.  

Please open a separate issue if you have a problem with the walkthrough document.  I checked and the above link seemed to work for me fine but maybe you're running it in some different way.
