### ISSUE TITLE
SIMD static functions only on S4TF toolchain

### ISSUE THREAD

**Issue by porterchild** [tensorflow/swift#404]
On the S4TF toolchain, I can use static transcendental functions on SIMD types like this:
`let powSimd = SIMD2.pow(mySimd, 2)`

On the normal Xcode toolchain, this is not available. A cursory exploration suggests that on the S4TF toolchain, SIMD types have been conformed to `ElementaryFunctions`, which is part of the `Numerics` library (is that true?).

Is there a way to get these functions on the normal Xcode toolchain? Are they on track to be mainlined? Are they only implemented on S4TF so far? `import Numerics` doesn't seem to give me those functions.

**Comment by dan-zheng** [comment]
Here's some context regarding `ElementaryFunctions`:

`ElementaryFunctions` protocol and conformances were [added](https://github.com/apple/swift/pull/23824) but then [removed](https://github.com/apple/swift/pull/26809) from `apple/swift` master branch. It's since been moved to [`apple/swift-numerics`](https://github.com/apple/swift-numerics/tree/master/Sources/RealModule).

`ElementaryFunctions` protocol and conformances were manually re-added to `apple/swift` tensorflow branch because [`tensorflow/swift-apis`](https://github.com/tensorflow/swift-apis) optimizers [depend on it](https://github.com/apple/swift/pull/26809#issuecomment-529728678). tensorflow branch also provides [`ElementaryFunctions` derived conformances](https://github.com/apple/swift/blob/tensorflow/lib/Sema/DerivedConformanceElementaryFunctions.cpp) ([examples](https://github.com/apple/swift/blob/tensorflow/test/Sema/struct_elementary_functions.swift)): we haven't taken time to pitch this via Swift Evolution to master branch yet.

---

> Is there a way to get these functions on the normal Xcode toolchain? Are they on track to be mainlined? Are they only implemented on S4TF so far? `import Numerics` doesn't seem to give me those functions.

When `ElementaryFunctions` was moved from `master` branch to [`apple/swift-numerics`](https://github.com/apple/swift-numerics), the [`SIMD{n}` conformances](https://github.com/apple/swift/blob/3e7cb166a69de3bf2c87456645b7586f8d48c9e0/stdlib/public/core/MathFunctions.swift.gyb#L133-L178) appear to have been dropped. I asked about re-adding those conformances to `apple/swift-numerics`: https://github.com/apple/swift-numerics/issues/103

All surprising behavior is due to ad-hoc differences between `apple/swift` tensorflow branch vs master branch. We should consider ways to eliminate these differences: adding `apple/swift-numerics` as an official dependency to `tensorflow/swift-apis`, pitching and upstreaming `ElementaryFunctions` derived conformances, etc.

**Comment by porterchild** [comment]
Could you point me to the code to do this?: 
> ElementaryFunctions protocol and conformances were manually re-added to apple/swift tensorflow branch

Would that just be a copy paste to add manually if I want to use those functions on the regular Xcode toolchain?

**Comment by dan-zheng** [comment]
Sure, here's the [gyb'd](https://nshipster.com/swift-gyb) code for [`SIMD{n}: ElementaryFunctions` conformances](https://github.com/apple/swift/blob/3e7cb166a69de3bf2c87456645b7586f8d48c9e0/stdlib/public/core/MathFunctions.swift.gyb#L133-L178).
Here's the [expanded Swift code](https://gist.github.com/dan-zheng/8161fdcc1ec76d278889158324326abf), I generated it locally on macOS.

> Would that just be a copy paste to add manually if I want to use those functions on the regular Xcode toolchain?

Yes, I believe so. This code probably won't work with S4TF toolchains though due to redefinition errors.

**Comment by porterchild** [comment]
Thanks Dan!

**Comment by dan-zheng** [comment]
Closing now, since the original question is really a feature request for `apple/swift-numerics`: https://github.com/apple/swift-numerics/issues/103.

> Is there a way to get these functions on the normal Xcode toolchain? Are they on track to be mainlined? Are they only implemented on S4TF so far? import Numerics doesn't seem to give me those functions.
