### ISSUE TITLE
S4TF doesn't support REPL anymore?

### ISSUE THREAD

**Issue by rahulbhalley** [tensorflow/swift#443]
I just installed Xcode 11 (May 3, 2020) Development Snapshot and I set the `swiftenv` to it. Now when I run `swift` in terminal I get the following error. Looks like S4TF is no longer supporting REPL but Colab/Jupyter. Why? REPL is cool. 

```
<unknown>:0: error: The Swift for TensorFlow toolchain does not support the Swift REPL. Colab (https://github.com/tensorflow/swift/blob/master/Usage.md#colaboratory) and Swift-Jupyter (https://github.com/google/swift-jupyter) are supported alternatives.
```

**Comment by marcrasi** [comment]
Hi!

We have temporarily dropped official support for the REPL in S4TF because it was a maintenance burden that was taking up a lot of our time, and Colab/Jupyter are similar enough to the REPL that it's not vital to continue supporting the REPL. Colab/Jupyter are one of the main distinguishing features of S4TF, so it's more valuable for us to spend our limited maintenance time on those.

(Examples of recent REPL breakages are https://bugs.swift.org/browse/TF-1185 and https://bugs.swift.org/browse/TF-1210).

The REPL will probably become more stable and easy to maintain as the S4TF toolchain converges with the main Swift toolchain. Once the maintenance burden becomes small enough, we should be able to reenable it.

That said, see https://github.com/apple/swift/pull/31358 for some ways to get around the error message and launch a Swift REPL. Just keep in mind that it may be broken, even in release toolchains, and that we won't prioritize fixes.

**Comment by rahulbhalley** [comment]
Alright.
