### ISSUE TITLE
Cannot verify swift-tensorflow with macOS Catalina

### ISSUE THREAD

**Issue by yos1p** [tensorflow/swift#467]
I downloaded swift-for-tensorflow v0.9 as stated in Installation.md. Apparently, when I tried to run the package installer this error comes up: 
this macOS cannot verify that this app is free from malware.

My macOS version is: 10.15.4

**Comment by dwbaron** [comment]
I have the same issue, I can't install the toolchain

**Comment by BradLarson** [comment]
In order to install the toolchain on macOS, you need to first try to open the installer package. This will display the error you encountered here. Then you need to go to System Preferences and open Security & Privacy. In the bottom half of that window, you'll see an entry for the toolchain package that you just tried to open. Choose to open it there, and you'll be presented with another dialog box where you can finally choose to open the package anyway and start the installer.

Sorry for the elaborate process, we've needed to do this for the last couple of major macOS versions due to issues with package signing.

**Comment by ematejska** [comment]
Per Brad's comment, this is the expected workflow right now.
