### ISSUE TITLE
Why archive?

### ISSUE THREAD

**Issue by Willian-Zhang** [tensorflow/swift#620]
This project seems to be very future promising and I have my all ears waiting for it to be production ready.

Instead, it goes archived.

Is there a specific reason for this?

**Comment by ProfFan** [comment]
TL;DR: Google got JAX and S4TF is too small a community. MLers all use Python and are not willing to learn Swift. So G killed the project.

Most of the team got reassigned to JAX instead.

There are still people who work on Differentiable Swift: PassiveLogic has their system completely built on Swift. But the S4TF effort is, sadly, over.

Differentiable programming is still live in Swift, and there is an NN library that is actively maintained by (one person) @liuliu

https://github.com/liuliu/s4nnc

Hope this is useful for you.

**Comment by saeta** [comment]
Thanks for the question @Willian-Zhang and we're also sorry that this project has been archived. I won't directly disagree with @ProfFan 's assessment, but I will say that the decision to archive this project was not due to a lack of interest or resources at Google, but were unfortunately due to concerns outside Google's control. Alas, I believe that's all that can be said at this point. Sorry!

Finally, @ProfFan is 100% spot on that differentiable Swift continues beyond the S4TF project (which we're _extremely_ happy about), and we continue to host binaries and toolchains to ensure folks who were depending on this project can continue to do what they need to do indefinitely (although neither I nor anyone else can commit to them being hosted in perpetuity).
