### ISSUE TITLE
internal error generating TensorFlow graph: GraphGen cannot lower a 'send' to the host yet

### ISSUE THREAD

**Issue by spprichard** [tensorflow/swift#8]
Hey All,

I am trying to run Swift for TensorFlow in a playground (notebook). The example I am interested in is the one found [here](https://github.com/tensorflow/swift/blob/master/docs/DesignOverview.md#the-tensorflow-module) 
```swift
import TensorFlow

var matrix: Tensor<Float> = [[1,2], [3,4]]

let sum = matrix + matrix
print("Sum: \(sum)")
```
When attempting to add 2 Tensors together I get the following error:
```
Playground execution failed:
error: TensorFlow.playground:5:18: error: internal error generating TensorFlow graph:
GraphGen cannot lower a 'send' to the host yet
let sum = matrix + matrix
                 ^
```
 Also, I highlight this issue [here](https://github.com/spprichard/Swift-For-Tensorflow) 
It appears to me that I am following the documentation exactly, unless I am missing something...Does anyone have any suggestions as to why this is happening? 

**UPDATE:**
There is a workaround for this highlighted [here](https://groups.google.com/a/tensorflow.org/forum/#!topic/swift/RrLq6DizjSk)

While this workaround "works" it doesn't seem like the "right" solution...just wanted to raise this issue in the proper place

_Note:_ Swift for TensorFlow Development Snapshot 2018-04-26

**Comment by rxwei** [comment]
Thank you! Wrapping top-level code into a function is usually a solution, because, from an implementation perspective, top-level variables have to be promoted from globals to SSA values in SIL to be "de-abstracted". 

The corresponding implementation is here, if you are interested in digging into the compiler:
https://github.com/google/swift/blob/a988b64966b1830cd379419e401d11efdca092d1/lib/SILOptimizer/Mandatory/TFDeabstraction.cpp#L902

@lattner will finish the deabstraction implementation. Once that's done, we can expect any user code to be properly handled according to the programming model.

**Comment by rxwei** [comment]
We will open a series of issues like "Implement proper deabstraction for top-level globals" in github.com/google/swift, which is the canonical compiler repo.
