### ISSUE TITLE
Trying TFiws example and getting property not differentiable

### ISSUE THREAD

**Issue by hiiroo** [tensorflow/swift#97]
Hello everyone, lately I was trying the example shown in Tensorflow Summit event (demo shown at 7:58 min of the video, https://www.youtube.com/watch?v=Yze693W4MaU). However, I get the error below with the toolchain  that created at 05.01.2019. I'm using it on xcode 10 with xcode 10 command line tools.

expression is not differentiable
    return 1/(1+exp(-x))
                ^
error: property is not differentiable

**Comment by rxwei** [comment]
We are actively fixing this issue. Standard library math functions do not have primitive derivatives defined for them because they are templated in the standard library and we don't support retroactive derivative registration yet. I wrote some explanation earlier on the mailing list:
https://groups.google.com/a/tensorflow.org/d/msg/swift/MOSpcVGktcU/4CVv_73jGwAJ

Retroactive derivative registration should be possible soon. In the meantime, you can run the same example on tensors.

**Comment by rxwei** [comment]
We added primitives in https://github.com/apple/swift/pull/22396. Things should be reproducible now.
